// Code generated by "stringer -trimprefix State -type State"; DO NOT EDIT.

package transaction

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateUnknown-0]
	_ = x[StatePending-1]
	_ = x[StateCommitted-2]
	_ = x[StateRolledBack-3]
}

const _State_name = "UnknownPendingCommittedRolledBack"

var _State_index = [...]uint8{0, 7, 14, 23, 33}

func (i State) String() string {
	if i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
