name: Tests
on: [push, pull_request]
jobs:
  test:
    name: Test on ${{ matrix.os }} with Go ${{ matrix.go_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [ 1.13, 1.14, 1.15 ]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go_version }}
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Test
      run: |
        go test -timeout 5m -race ./...
